import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(root, "../pkg/docx_wasm_bg.wasm");
const gluePath = join(root, "../pkg/docx_wasm.js");
const outputPath = join(root, "../src/wasm-bytes.ts");

const wasmBytes = readFileSync(wasmPath);
const encoded = wasmBytes.toString("base64");

writeFileSync(
  outputPath,
  `// Generated by scripts/inline-wasm.mjs — do not edit.\nexport const WASM_BYTES_BASE64 = ${JSON.stringify(encoded)};\n`
);

// Strip wasm-bindgen's `new URL('docx_wasm_bg.wasm', import.meta.url)` fallback.
// initWasm always passes the inlined bytes, so the fallback is dead code — but
// bundlers (webpack, Next.js) statically resolve the URL asset and fail the
// consumer's build because the .wasm binary is not shipped in the package.
const glue = readFileSync(gluePath, "utf8");
const fallbackPattern =
  /module_or_path = new URL\('docx_wasm_bg\.wasm', import\.meta\.url\);/;
if (!fallbackPattern.test(glue)) {
  throw new Error(
    "inline-wasm: expected wasm URL fallback not found in pkg/docx_wasm.js — wasm-bindgen output may have changed; update this script"
  );
}
writeFileSync(
  gluePath,
  glue.replace(
    fallbackPattern,
    "throw new Error('react-docx wasm: initWasm must be called with inlined wasm bytes');"
  )
);
