import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(root, "../pkg/docx_wasm_bg.wasm");
const outputPath = join(root, "../src/wasm-bytes.ts");

const wasmBytes = readFileSync(wasmPath);
const encoded = wasmBytes.toString("base64");

writeFileSync(
  outputPath,
  `// Generated by scripts/inline-wasm.mjs — do not edit.\nexport const WASM_BYTES_BASE64 = ${JSON.stringify(encoded)};\n`
);
